---
- name: Install Nginx
  hosts: web
  become: true
  gather_facts: true

  tasks:
    - name: Install Nginx on Target Node
      package:
        name: nginx
        state: present

    - name: Start and Enable Nginx Service
      service:
        name: nginx
        state: started
        enabled: true