name: Ansible Deploy (Web=Nginx, App=Java)

on:
  workflow_dispatch: {}
  push:
   branches: ["work"]

jobs:
  run-ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4



      - name: Install Ansible
        run: |
          apt install ansible -y
          ansible --version
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          
      - name: Create inventory.ini
        run: |
          cat > inventory.ini <<EOF
          [ec2]
          target ansible_host=34.241.60.43 ansible_user=ec2-user ansible_ssh_private_key_file=key.pem
          EOF
          cat inventory.ini

      - name: Run playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          
        run: |
          ansible --version
          ansible-playbook -i inventory.ini install.yml -C